# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ys, fishy, avit pygmalion
ZSH_THEME="fishy"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git autojump)

# User configuration

export PATH=$HOME/bin:/usr/local/bin:$PATH
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# for Compilation
# export ARCHFLAGS="-arch x86_64"

# for Java
export JAVA_HOME=/usr/lib/jvm/java-8-sun
export JRE_HOME=${JAVA_HOME}/jre
export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib
export PATH=${JAVA_HOME}/bin:$PATH

alias gcms='cloneMyself() { git clone git@github.com:wikinee/$1.git ${2:-$1}     ; }; cloneMyself'
alias cc='reset'
alias vi='vim'

# for clipboard
# xclip 不加选项时只在保存在X PRIMARY（应该是终端剪切板）
# 加上选项 -selection c后保存在 X CLIPBOARD（应该是外部程序剪切板)
alias pbcopy='xclip -selection c '
alias pbpast='xclip -selection c -o'

# self define cmake clean
alias cmakeCleanAll='rm -rf CMakeCache.txt Makefile CMakeFiles cmake_install.cmake'
alias cmakeClean='find .  -name "CMakeCache.txt" -exec rm -rf {} \;'
export TERM=xterm-256color

# for Linux
export EDITOR="vim"
export TERM=xterm-256color

# for Debian
# alias clearConfig="dpkg -l | grep \"^rc\"| awk \"{print $2}\" | xargs sudo aptitude -y purge"

# for SSH
# export SSH_KEY_PATH="~/.ssh/dsa_id"
function toLaji()
{
	scp $1 SOMENAME@Laji:~
}
alias to-laji=toLaji $1;

# for Golang
export GO111MODULE=on
export GOPROXY=https://goproxy.cn
export GOROOT=/usr/local/go
export GOPATH=$HOME/Go

# for Mirrors
alias cnpm="npm --registry=https://registry.npm.taobao.org \
            --cache=$HOME/.npm/.cache/cnpm \
            --disturl=https://npm.taobao.org/dist \
            --userconfig=$HOME/.cnpmrc"
export HOMEBREW_BOTTLE_DOMAIN='https://mirrors.ustc.edu.cn/homebrew-bottles'

# for Qt
# export PATH="/usr/local/opt/qt/bin:$PATH"

# for Debian
DEBMAIL="neeyongliang@gmail.com"
DEBFULLNAME="wikinee"

# for GPG2
alias gpg='gpg2'
